version: '3'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./docker/nginx-proxy/cert/:/etc/nginx/certs/
    networks:
      - web

  nginx:
    image: nginx:1.19
    restart: on-failure
    volumes:
      - .:/home/app
      - ./docker/nginx/conf/site.conf:/etc/nginx/conf.d/site.conf
    links:
      - php
    networks:
      - web

  php:
    build: docker/php
    restart: on-failure
    working_dir: /home/app
    volumes:
      - .:/home/app
    networks:
      - web

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    volumes:
      - .:/home/app
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    networks:
      - web

  quality-assurance:
    build: docker/quality-assurance
    volumes:
      - .:/project

networks:
    web: