imports:
    - { resource: services.yaml }

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Domain\EmbedInterface: '@App\Infrastructure\Embed\FakeEmbed'
