services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    'App\Domain\ValueObject\Link\EmbedInterface': '@App\Infrastructure\Embed\FakeEmbed'
