services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Behat\:
        resource: '../tests/Behat/*'

    App\Tests\Bookmark\BookmarkProperty: ~

    App\Bookmark\BookmarkPropertyInterface: '@App\Tests\Bookmark\BookmarkProperty'